# This is a basic workflow to help you get started with Actions

name: Update .gov zone file from CZDS API
run-name: Download .gov zone file from CZDS API and upload to dotgov-data

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "5 6 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Delete later: Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Downloads the current .gov zone file from CZDS
      - name: Download gov.txt.gz from CZDS API
        env:
            ICANN_USERNAME: ${{ secrets[env.ICANN_USERNAME] }}
            ICANN_PASSWORD: ${{ secrets[env.ICANN_PASSWORD] }}
        run: |
          chmod +x ./scripts/download_zone_file.sh
          ./scripts/download_zone_file.sh ${{ secrets[env.ICANN_USERNAME] }} ${{ secrets[env.ICANN_PASSWORD] }}
        shell: sh

      # Uploads the .gov zone file to Github artifact gov_zone_file
      - name: Upload retrieved .gov zone file
        uses: actions/upload-artifact@v4
        with:
          name: gov_zone_file
          path: gov.zone.txt.gz
